# Generated by Django 2.0.5 on 2018-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20180809_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='feature_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pix', verbose_name='Feature'),
        ),
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.NullBooleanField(),
        ),
    ]
