# Generated by Django 2.0.5 on 2018-08-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20180813_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pix', verbose_name='Photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo8',
        ),
        migrations.AddField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.Car'),
        ),
    ]
